### ISSUE TITLE
Wait::ResultInvalid Error

### ISSUE THREAD

**Issue by jeffmikels** [toddmazierski/mint-exporter#16] opened 2016-05-25 17:54 UTC
I just grabbed the latest repo and followed the instructions to install it as a standalone utility. However, when I run it, I get this error:

```
/home/jeff/tmp/mint-exporter/vendor/bundle/ruby/2.2.0/gems/wait-0.5.2/lib/wait.rb:136:in `until': Wait::ResultInvalid (Wait::ResultInvalid)
    from /home/jeff/tmp/mint-exporter/lib/mint/transaction.rb:22:in `request_until_valid'
    from /home/jeff/tmp/mint-exporter/lib/mint/transaction.rb:12:in `fetch'
    from mint-exporter.rb:9:in `<main>'
```

Any suggestions?

**Comment by c4mb0t** [comment] 2016-06-03 18:56
Same thing happens to me. Think it is caused by a recent change to the mint.com log in API. More info here: https://github.com/mrooney/mintapi/issues/73

**Comment by toddmazierski** [comment] 2016-06-11 16:40
Yikes! Thanks for filing a bug, @jeffmikels, and thanks for the link, @c4mb0t!

To summarize: approximately 2 weeks ago, Mint.com strengthened their authentication with a variety of challenge mechanisms, including CAPTCHAs and [multi-factor authentication](https://mint.lc.intuit.com/announcements/1286158). This is a good thing! But not a good thing for hacks like this project. :smile: 

I've subscribed to that mintapi GitHub issue in hopes a reliable, clean, and concise solution comes along. In the meantime:

* [mint-getaccounts-casper](https://github.com/deftx/mint-getaccounts-casper) has emerged as a possible alternative
* I'm open to contributions

**Comment by toddmazierski** [comment] 2019-01-08 03:51
Closing this issue as this project is no longer maintained. Of potential interest to the participants may be this [Build Your Own Mint](https://github.com/yyx990803/build-your-own-mint) project. Good luck!

**Closed by toddmazierski** 2019-01-08 03:51 UTC
